/*
 * This file is generated by jOOQ.
 */
package de.crafted.api.service.image.jooq;


import de.crafted.api.service.image.jooq.tables.Image;
import de.crafted.api.service.image.jooq.tables.TicketImage;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>image</code>.
     */
    public static final Image IMAGE = Image.IMAGE;

    /**
     * The table <code>ticket_image</code>.
     */
    public static final TicketImage TICKET_IMAGE = TicketImage.TICKET_IMAGE;
}
