/*
 * This file is generated by jOOQ.
 */
package de.crafted.api.service.user.jooq;


import de.crafted.api.service.user.jooq.tables.User;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user</code>.
     */
    public static final User USER = User.USER;
}
