/*
 * This file is generated by jOOQ.
 */
package de.crafted.api.service.ticket.jooq;


import de.crafted.api.service.ticket.jooq.tables.Ticket;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ticket</code>.
     */
    public static final Ticket TICKET = Ticket.TICKET;
}
