/*
 * This file is generated by jOOQ.
 */
package de.crafted.api.service.user.jooq.tables.records;


import de.crafted.api.service.user.jooq.tables.User;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record9<Long, String, String, String, Boolean, LocalDateTime, LocalDateTime, Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user.subject</code>.
     */
    public void setSubject(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.subject</code>.
     */
    public String getSubject() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.verified</code>.
     */
    public void setVerified(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>user.verified</code>.
     */
    public Boolean getVerified() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>user.user_create_date</code>.
     */
    public void setUserCreateDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>user.user_create_date</code>.
     */
    public LocalDateTime getUserCreateDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>user.user_last_modified_date</code>.
     */
    public void setUserLastModifiedDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>user.user_last_modified_date</code>.
     */
    public LocalDateTime getUserLastModifiedDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>user.image_id</code>.
     */
    public void setImageId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>user.image_id</code>.
     */
    public Long getImageId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>user.rating</code>.
     */
    public void setRating(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>user.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, Boolean, LocalDateTime, LocalDateTime, Long, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, Boolean, LocalDateTime, LocalDateTime, Long, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.SUBJECT;
    }

    @Override
    public Field<String> field3() {
        return User.USER.USERNAME;
    }

    @Override
    public Field<String> field4() {
        return User.USER.DESCRIPTION;
    }

    @Override
    public Field<Boolean> field5() {
        return User.USER.VERIFIED;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return User.USER.USER_CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return User.USER.USER_LAST_MODIFIED_DATE;
    }

    @Override
    public Field<Long> field8() {
        return User.USER.IMAGE_ID;
    }

    @Override
    public Field<Integer> field9() {
        return User.USER.RATING;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSubject();
    }

    @Override
    public String component3() {
        return getUsername();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Boolean component5() {
        return getVerified();
    }

    @Override
    public LocalDateTime component6() {
        return getUserCreateDate();
    }

    @Override
    public LocalDateTime component7() {
        return getUserLastModifiedDate();
    }

    @Override
    public Long component8() {
        return getImageId();
    }

    @Override
    public Integer component9() {
        return getRating();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSubject();
    }

    @Override
    public String value3() {
        return getUsername();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public Boolean value5() {
        return getVerified();
    }

    @Override
    public LocalDateTime value6() {
        return getUserCreateDate();
    }

    @Override
    public LocalDateTime value7() {
        return getUserLastModifiedDate();
    }

    @Override
    public Long value8() {
        return getImageId();
    }

    @Override
    public Integer value9() {
        return getRating();
    }

    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public UserRecord value5(Boolean value) {
        setVerified(value);
        return this;
    }

    @Override
    public UserRecord value6(LocalDateTime value) {
        setUserCreateDate(value);
        return this;
    }

    @Override
    public UserRecord value7(LocalDateTime value) {
        setUserLastModifiedDate(value);
        return this;
    }

    @Override
    public UserRecord value8(Long value) {
        setImageId(value);
        return this;
    }

    @Override
    public UserRecord value9(Integer value) {
        setRating(value);
        return this;
    }

    @Override
    public UserRecord values(Long value1, String value2, String value3, String value4, Boolean value5, LocalDateTime value6, LocalDateTime value7, Long value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, String subject, String username, String description, Boolean verified, LocalDateTime userCreateDate, LocalDateTime userLastModifiedDate, Long imageId, Integer rating) {
        super(User.USER);

        setId(id);
        setSubject(subject);
        setUsername(username);
        setDescription(description);
        setVerified(verified);
        setUserCreateDate(userCreateDate);
        setUserLastModifiedDate(userLastModifiedDate);
        setImageId(imageId);
        setRating(rating);
    }
}
