/*
 * This file is generated by jOOQ.
 */
package de.crafted.api.service.common.jooq;


import de.crafted.api.service.common.jooq.tables.TicketTag;
import de.crafted.api.service.common.jooq.tables.UserTag;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ticket_tag</code>.
     */
    public static final TicketTag TICKET_TAG = TicketTag.TICKET_TAG;

    /**
     * The table <code>user_tag</code>.
     */
    public static final UserTag USER_TAG = UserTag.USER_TAG;
}
